### ISSUE TITLE
[BUG] Pinging a stealth host provides no live feedback

### ISSUE THREAD

**Issue by TurtleWilly** [denilsonsa/prettyping#36] opened 2023-08-25 19:08 UTC
When pinging a host that has IDCMP blocked (e.g. one activates the stealth option on Mac OS X's firewall settings), then running `prettyping host` will just dump the legend and then nothing happens… just sits there.

First when one hits CTRL-C after getting bored prettyping will dump a series of red exclamation marks.

Probably some flush command is missing here when generating that particular output, so things only get flushed in one go at the very end.

**Comment by denilsonsa** [comment] 2023-08-25 20:31
I think in this case it is (unfortunately) working as intended. If you call `ping` on that host, would it print anything? If it doesn't print anything, then `prettyping` can't print anything either.

A "solution" would be to pass some parameter that would make the underlying ping print a timeout message or something. (Like `ping -W <timeout>` on Linux, no idea about Mac.) Or try using a different ping implementation `--pingbin …`. (I vaguely remember `oping` printing messages in such cases, but I may be wrong.)

Sidenote: `prettyping` can't implement a timeout, it must come from the underlying `ping`. And the timeout can be quite long, as there is [record of some ping responses taking almost two hours](https://en.wikipedia.org/wiki/IP_over_Avian_Carriers#Real-life_implementation). Okay, this is an extreme case, and I don't think anyone actually uses [IPoAC](https://en.wikipedia.org/wiki/IP_over_Avian_Carriers), but it illustrates the point.

Since I think in this case there is nothing to be done, I'm closing this issue. Feel free to reopen if you have any further information about it.

**Closed by denilsonsa** 2023-08-25 20:31 UTC

**Comment by TurtleWilly** [comment] 2023-08-25 22:46
Ping works properly and gives me live updates:

```
$ ping localhost
PING localhost (127.0.0.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
^C
--- localhost ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
```

After each 'request timeout' it prints the line. I'm afraid it's an issue in prettyping.
